**Practical 1 - Revisiting Pandas and Numpy**


**Step-1** : Importing the necessary libraries.
             Pandas (pd) is used to create and manage DataFrames.
             NumPy (np) is used for numerical and matrix operations such as addition, multiplication, transpose, and inverse.

In [ ]:
import pandas as pd
import numpy as np


**Step-2**: Create a dataset.data stores the raw numerical values in rows and columns. pd.DataFrame() converts the raw data into a DataFrame. columns=["A", "B", "C"] assigns names to the three columns.

In [ ]:
data = [
    [2, 4, 5],
    [6, 8, 9],
    [7, 5, 6],

]

df = pd.DataFrame(data, columns=["A", "B", "C"])

print("DataFrame:")
print(df)

DataFrame:
   A  B  C
0  2  4  5
1  6  8  9
2  7  5  6


**Step 3**: Convert DataFrame to NumPy Array. df.to_numpy() converts the Pandas DataFrame into a NumPy array.
The array is stored in the variable arr.

In [ ]:
arr = df.to_numpy()

print("\nNumPy Array:")
print(arr)


NumPy Array:
[[2 4 5]
 [6 8 9]
 [7 5 6]]


**Step 4**: Finding Shape, Size and Dimension. arr.shape → shows the number of rows and columns.
arr.size → shows the total number of elements.
arr.ndim → shows the number of dimensions.

In [ ]:
print("\nShape:", arr.shape)
print("Size:", arr.size)
print("Dimension:", arr.ndim)


Shape: (3, 3)
Size: 9
Dimension: 2


**Step-5**: Performing operations using numpy.


**1. Addition:-** arr + arr performs element-wise addition of the array with itself.
The result is stored in the variable addition.

In [ ]:
addition = arr + arr

print("\nAddition:")
print(addition)


Addition:
[[ 4  8 10]
 [12 16 18]
 [14 10 12]]


**2. Subtraction:-** arr - arr performs element-wise subtraction.The result is stored in variable subtraction.

In [ ]:
subtraction = arr - arr

print("\nSubtraction:")
print(subtraction)


Subtraction:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


**3. Multiplication:-** Each value is multiplied by the corresponding value in the same array.

In [ ]:
multiplication = arr * arr

print("\nMultiplication:")
print(multiplication)


Multiplication:
[[ 4 16 25]
 [36 64 81]
 [49 25 36]]


**4. Transpose:-** Transpose flips the rows and columns of the matrix.arr.T calculates the transpose of the array.

In [ ]:
transpose = arr.T

print("\nTranspose:")
print(transpose)


Transpose:
[[2 6 7]
 [4 8 5]
 [5 9 6]]


**5. Inverse:-** linalg → NumPy's linear algebra functions.
inv() → finds the inverse

In [ ]:
inverse = np.linalg.inv(arr)

print("Inverse:")
print(inverse)


Inverse:
[[-0.1875 -0.0625  0.25  ]
 [-1.6875  1.4375 -0.75  ]
 [ 1.625  -1.125   0.5   ]]


**6. Product:-** np.dot(arr, arr) performs matrix multiplication of the array with itself.
The result is stored in the variable product.

In [ ]:
product = np.dot(arr, arr)

print("\nMatrix Product:")
print(product)


Matrix Product:
[[ 63  65  76]
 [123 133 156]
 [ 86  98 116]]
